/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
#define ENABLE_NLS 1

/* Define if the GNU dcgettext() function is already present or preinstalled.
   */
#define HAVE_DCGETTEXT 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Define if you have the iconv() function. */
/* #undef HAVE_ICONV */

/* Define to 1 if you have the 'xml2' library (-lxml2). */
#define HAVE_LIBXML2 1

/* Name of package */
#define PACKAGE "gworldclock"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "gworldclock"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "gworldclock 3.0.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "gworldclock"

/* Define to the home page for this package. */
/* #undef PACKAGE_URL */

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.0.0"

/* 18 March 2005 */
#define RELEASE_DATE "18 March 2005"

/* Version number of package */
#define VERSION "1.4.3"
